### ISSUE TITLE
Can't open Morphologie 1.1…but it works…

### ISSUE THREAD

**Issue by smalllotus** [openmusic-project/Morphologie#9]
hi,

I have this issue when i load Morphologie 1.1

![image](https://user-images.githubusercontent.com/46628903/102013691-0c6cc680-3d52-11eb-927e-235fbb5f3c39.png)

but, even if Morphologie seems not to be loaded, it works : 

![image](https://user-images.githubusercontent.com/46628903/102013950-88b3d980-3d53-11eb-9260-e6ccdb509822.png)

weird, isn't it ?

best,

Jerome

**Comment by FredVoisin** [comment]
Hi,

yes, this error comes from some not so good cosmetic conversion of some italian characters in UTF-8, which appear in some function's doc string so that it has no effect in the evaluation of these functions.
It will be fixed asap, by replacing the special chars used italian by more standard characters, or by translationg the italian doc in english.

Fred

**Comment by j-bresson** [comment]
I have updated the 1.1 release. I hope this will work now. 
Let's follow-up about this on #6 if necessary.
